### Get list of all cabins
GET https://localhost:44378/cabins HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcyMWZlZGEwN2I4MDAwMzUwYjllOWEiLCJlbWFpbCI6InBlZ2d5X2hvcGtpbnNAZXhhbXBsZS5vcmciLCJpYXQiOjE2MDE0MTIwNzEsImV4cCI6MTYwMTQxMjk3MX0.TaVxC2yKTObYuLDAh1msXvSYoO2ik0xg5n1uY5TIdC0

### Get list of all cabins that an email owns
GET https://localhost:44378/cabins/something@qwe.com HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcyMWZlZGEwN2I4MDAwMzUwYjllOWEiLCJlbWFpbCI6InBlZ2d5X2hvcGtpbnNAZXhhbXBsZS5vcmciLCJpYXQiOjE2MDE0MTIwNzEsImV4cCI6MTYwMTQxMjk3MX0.TaVxC2yKTObYuLDAh1msXvSYoO2ik0xg5n1uY5TIdC0

### Get all services
GET https://localhost:44378/services HTTP/1.1

### Create a new service
POST https://localhost:44378/services HTTP/1.1
Content-Type: application/json


{
"ServiceType": "Chimney sweeping",
"Description": "Sweeping chimneys ONLY old ones i lkike em",
"Price": 2,
"PriceUnit": "Per Chimney",
"Company": "Old Pipes ltd."
}

### Update a service
PUT https://localhost:44378/services/4 HTTP/1.1
Content-Type: application/json


{

}
### Delete a service
DELETE https://localhost:44378/services/5 HTTP/1.1